const events=[
 {name:"EPINOIA: The Hackathon Event",tag:"LIVE NOW",type:"Offline",location:"IIM Indore",dates:"Sep 13 – Sep 19, 2026",end:"2026-09-19",prize:"₹25,000",skills:"Innovation · Engineering",url:"https://unstop.com/hackathons"},
 {name:"YC Fall 2026 x Moss: The Zero Latency Builder Sprint",tag:"6 DAYS LEFT",type:"Online / Bengaluru",location:"Bengaluru, India",dates:"Sep 14 – Sep 21, 2026",end:"2026-09-21",prize:"₹50,000",skills:"AI · Builders",url:"https://devpost.com/hackathons"},
 {name:"Agentic AI Hackathon",tag:"ENDING SOON",type:"Online",location:"Online",dates:"Sep 9 – Sep 20, 2026",end:"2026-09-20",prize:"₹80,000",skills:"AI · Agents",url:"https://unstop.com/hackathons"},
 {name:"Qiskit Fall Fest 2026",tag:"STUDENT",type:"Offline",location:"SRM University, Amaravati",dates:"Sep 12 – Sep 26, 2026",end:"2026-09-26",prize:"—",skills:"Quantum · Computing",url:"https://unstop.com/hackathons"},
 {name:"ACM Marketsphere 2026",tag:"INDIA",type:"Online",location:"RV College of Engineering, Bengaluru",dates:"Sep 9 – Sep 26, 2026",end:"2026-09-26",prize:"₹20,000",skills:"Markets · Tech",url:"https://unstop.com/hackathons"},
 {name:"DataHeist",tag:"30 DAYS LEFT",type:"Offline",location:"DTU, New Delhi",dates:"Sep 12 – Oct 16, 2026",end:"2026-10-16",prize:"—",skills:"Data · Analytics",url:"https://unstop.com/hackathons"},
 {name:"Hacktopia 2026",tag:"15 DAYS LEFT",type:"Offline",location:"PCCOE, Pune",dates:"Sep 5 – Sep 30, 2026",end:"2026-09-30",prize:"₹25,000",skills:"Software · Innovation",url:"https://unstop.com/hackathons"},
 {name:"Hack Era 1.0",tag:"25 DAYS LEFT",type:"Online",location:"Online",dates:"Sep 12 – Oct 13, 2026",end:"2026-10-13",prize:"—",skills:"Open Innovation",url:"https://unstop.com/hackathons"}
];
const grid=document.getElementById("hackGrid");const savedKey="skillbridge_saved_hackathons";let saved=JSON.parse(localStorage.getItem(savedKey)||"[]");let filter="all",query="";
function daysLeft(end){return Math.max(0,Math.ceil((new Date(end+"T23:59:59")-new Date())/86400000))}
function renderHackathons(){const items=events.filter(e=>(filter==="all"|| (filter==="saved"?saved.includes(e.name):filter===e.type.toLowerCase()))&&(`${e.name} ${e.skills} ${e.location}`.toLowerCase().includes(query)));grid.innerHTML=items.map(e=>{const left=daysLeft(e.end),isSaved=saved.includes(e.name),live=left>0;return `<article class="hack-card interactive-card"><div class="hack-card-top"><span class="hack-card-icon"><span class="material-symbols-outlined">emoji_events</span></span><span class="page-chip">${e.tag}</span></div><h2>${e.name}</h2><p>${e.skills}</p><div class="hack-meta-row"><span class="hack-meta">📅 ${e.dates}</span><span class="hack-meta">📍 ${e.location}</span><span class="hack-meta">🏆 ${e.prize}</span></div><div class="hack-card-foot"><span>${live?`${left} day${left===1?"":"s"} left`:`Event ended`}</span><div style="display:flex;gap:7px;align-items:center"><button class="hack-save ${isSaved?"saved":""}" data-save="${e.name}">${isSaved?"★ Saved":"☆ Save"}</button><a href="${e.url}" target="_blank" rel="noopener">Open website ↗</a></div></div></article>`}).join("")||`<div class="library-empty">No hackathons match this filter.</div>`;grid.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>{const n=b.dataset.save;saved=saved.includes(n)?saved.filter(x=>x!==n):[...saved,n];localStorage.setItem(savedKey,JSON.stringify(saved));renderHackathons()})}
function setupHackathonUI(){const main=document.querySelector(".page-main");if(!main)return;const toolbar=document.createElement("div");toolbar.className="hack-toolbar";toolbar.innerHTML=`<div class="hack-filters"><button class="hack-filter active" data-hf="all">All</button><button class="hack-filter" data-hf="online">Online</button><button class="hack-filter" data-hf="offline">Offline</button><button class="hack-filter" data-hf="saved">Saved</button></div><input class="hack-search" id="hackSearch" placeholder="Search AI, data, Bengaluru...">`;document.getElementById("hackGrid").before(toolbar);toolbar.querySelectorAll(".hack-filter").forEach(b=>b.onclick=()=>{filter=b.dataset.hf;toolbar.querySelectorAll(".hack-filter").forEach(x=>x.classList.toggle("active",x===b));renderHackathons()});toolbar.querySelector("#hackSearch").oninput=e=>{query=e.target.value.toLowerCase().trim();renderHackathons()};const live=events.find(e=>daysLeft(e.end)>0);const hero=document.createElement("section");hero.className="hack-live-card";hero.innerHTML=`<div><span class="hack-live-badge">● LIVE OPPORTUNITY</span><h2>${live.name}</h2><p>${live.dates} · ${live.location} · ${live.prize}</p></div><a class="page-btn" href="${live.url}" target="_blank" rel="noopener">View opportunity ↗</a>`;document.getElementById("hackGrid").before(hero);renderHackathons()}
setupHackathonUI();
