const savedProfile=localStorage.getItem("skillbridge_profile");
const noProfile=document.getElementById("noProfile"),content=document.getElementById("roadmapContent");
let profile=null;
try { profile=savedProfile?JSON.parse(savedProfile):null; } catch (error) { console.error("Saved profile is invalid:",error); localStorage.removeItem("skillbridge_profile"); }
if(!profile||!profile.targetRole) noProfile.classList.remove("hidden"); else {content.classList.remove("hidden");loadRoadmap(profile);}
async function loadRoadmap(profile){try{const [roles,projects]=await Promise.all([fetch("data/roles.json").then(r=>{if(!r.ok)throw new Error("Could not load roles");return r.json()}),fetch("data/projects.json").then(r=>{if(!r.ok)throw new Error("Could not load projects");return r.json()})]);const quizzes=JSON.parse(localStorage.getItem("skillbridge_quiz_results")||"{}");const started=JSON.parse(localStorage.getItem("skillbridge_started_skills")||"[]");const have=new Set((profile.skills||[]).map(s=>s.toLowerCase().trim()));const required=roles[profile.targetRole]||[];if(!required.length)throw new Error("Select a supported target role in Settings");const results=required.map((skill,index)=>{const quiz=quizzes[skill],done=have.has(skill.toLowerCase())||quiz?.verified;return{skill,step:index+1,status:done?"completed":(started.includes(skill)||quiz?"active":"upcoming"),project:projects[skill]||null,quizScore:quiz?.score}});renderRoadmap(profile,results)}catch(error){console.error(error);content.innerHTML=`<div class="roadmap-empty"><h1>Your roadmap needs one small fix</h1><p>${error.message}. Open Settings, save your target role, then return here.</p><a href="index.html">Open Settings →</a></div>`}}
function renderRoadmap(profile,results){const complete=results.filter(x=>x.status==="completed").length,active=results.filter(x=>x.status==="active").length,percent=results.length?Math.round(complete/results.length*100):0,next=results.find(x=>x.status!=="completed");document.getElementById("roleHeading").textContent=`${profile.targetRole} roadmap`;document.getElementById("roleSubtitle").textContent=`A practical plan for ${profile.name||"you"}, built from the skills employers expect.`;document.getElementById("progressPercent").textContent=`${percent}%`;document.getElementById("progressLabel").textContent=complete?`You have completed ${complete} of ${results.length} milestones. Keep the pace.`:`Start with one focused session today — your path will grow from there.`;document.getElementById("progressFill").style.width=`${percent}%`;document.getElementById("completeCount").textContent=complete;document.getElementById("remainingCount").textContent=results.length-complete;document.getElementById("daysEstimate").textContent=`${results.filter(x=>x.status!=="completed").reduce((a,x)=>a+(x.project?.days||5),0)} days`;document.getElementById("roadmapStatus").textContent=`${complete} done · ${active} in progress · ${results.length} steps`;renderFocus(next);renderSkills(results);}
function renderFocus(next){const title=document.getElementById("focusSkill"),desc=document.getElementById("focusDescription"),video=document.getElementById("focusVideo"),project=document.getElementById("focusProject");if(!next){title.textContent="You’ve completed every milestone";desc.textContent="Great work. Build a project or retake an assessment to deepen your skills.";video.href="projects.html";video.textContent="Browse projects →";project.href="assessment.html";project.textContent="Review skills →";return}title.textContent=`Focus on ${next.skill} next`;desc.textContent=next.project?`${next.project.project} · about ${next.project.days} days. Small practical work makes this stick.`:`Start with a focused beginner lesson and apply what you learn.`;video.href=`https://www.youtube.com/results?search_query=${encodeURIComponent(next.skill+" full course for beginners")}`;project.href=`projects.html?q=${encodeURIComponent(next.skill+" project")}`;}
function renderSkills(results){const list=document.getElementById("skillList");list.innerHTML=results.map(r=>{const label={completed:"Completed",active:"In progress",upcoming:"Up next"}[r.status];const project=r.project?`${r.project.level} · ~${r.project.days} days`:`Foundation skill`;const action=r.status==="completed"?`<a href="assessment.html">Review</a>`:r.status==="active"?`<a href="learn.html#${encodeURIComponent(r.skill)}">Continue</a>`:`<button data-skill="${r.skill}">Start step</button>`;return`<article class="roadmap-skill ${r.status}"><div class="roadmap-skill-index">${r.status==="completed"?"✓":r.step}</div><div><h3>${r.skill} <span class="roadmap-chip ${r.status}">${label}</span></h3><p>${project}${r.quizScore!==undefined?` · assessment ${r.quizScore}%`:""}</p></div><div class="skill-actions">${action}</div></article>`}).join("");list.querySelectorAll("button[data-skill]").forEach(button=>button.onclick=()=>startSkill(button.dataset.skill));}
function startSkill(skill){const started=JSON.parse(localStorage.getItem("skillbridge_started_skills")||"[]");if(!started.includes(skill))started.push(skill);localStorage.setItem("skillbridge_started_skills",JSON.stringify(started));window.location.hash=encodeURIComponent(skill);window.location.reload();}
