import { auth, db } from "./firebase-config.js";
import { doc, setDoc, getDoc } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
let currentSkills=[],avatar="";
const $=id=>document.getElementById(id);
function initials(name="SkillBridge"){return name.split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function renderAvatar(){const img=$("avatarImage"),initial=$("avatarInitials");initial.textContent=initials($("name").value);if(avatar){img.src=avatar;img.classList.add("show")}else{img.removeAttribute("src");img.classList.remove("show")}}
function renderSkills(){$("skillTags").innerHTML=currentSkills.map((skill,i)=>`<span class="skill-tag">${skill}<button type="button" data-i="${i}" aria-label="Remove ${skill}">×</button></span>`).join("");document.querySelectorAll("#skillTags button").forEach(b=>b.onclick=()=>{currentSkills.splice(+b.dataset.i,1);renderSkills()})}
function fill(profile,user){$("name").value=profile.name||"";$("email").value=user.email||profile.email||"";$("education").value=profile.education||"";$("branch").value=profile.branch||"";$("year").value=profile.year||"";$("targetRole").value=profile.targetRole||"";currentSkills=profile.skills||[];avatar=profile.avatar||"";renderSkills();renderAvatar()}
function addSkill(){const value=$("skillInput").value.trim();if(value&&!currentSkills.some(s=>s.toLowerCase()===value.toLowerCase())){currentSkills.push(value);renderSkills()}$("skillInput").value=""}
$("addSkillBtn").onclick=addSkill;$("skillInput").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addSkill()}};$("name").oninput=renderAvatar;
$("avatarInput").onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>3*1024*1024){alert("Please choose an image smaller than 3 MB.");e.target.value="";return}const image=new Image();image.onload=()=>{const size=Math.min(320,Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=canvas.height=size;const ctx=canvas.getContext("2d"),scale=Math.max(size/image.width,size/image.height),w=image.width*scale,h=image.height*scale;ctx.drawImage(image,(size-w)/2,(size-h)/2,w,h);avatar=canvas.toDataURL("image/jpeg",.8);renderAvatar()};image.src=URL.createObjectURL(file)};
$("removePhoto").onclick=()=>{avatar="";$("avatarInput").value="";renderAvatar()};
onAuthStateChanged(auth,async user=>{if(!user)return;const cached=JSON.parse(localStorage.getItem("skillbridge_profile")||"{}");try{const snap=await getDoc(doc(db,"profiles",user.uid));fill(snap.exists()?{...cached,...snap.data()}:cached,user)}catch{fill(cached,user)}});
$("profileForm").onsubmit=async e=>{e.preventDefault();const user=auth.currentUser;if(!user)return;const profile={name:$("name").value.trim(),education:$("education").value.trim(),branch:$("branch").value.trim(),year:$("year").value,targetRole:$("targetRole").value,skills:currentSkills,email:user.email,avatar};try{await setDoc(doc(db,"profiles",user.uid),profile,{merge:true});localStorage.setItem("skillbridge_profile",JSON.stringify(profile));$("savedMessage").textContent="Changes saved — your plan is up to date.";if(window.SkillBridgeGamification)window.SkillBridgeGamification.addXP(10,"Settings updated")}catch(err){console.error(err);$("savedMessage").textContent="Couldn’t save right now. Please try again."}};
